import dedent from 'dedent';

export const EXTENSION_TO_LANG: Record<string, string> = {
	html: 'html',
	htm: 'html',
	componenthtml: 'angular-html',
	componentts: 'angular-ts',
	astro: 'astro',
	bladephp: 'blade',
	c: 'c',
	h: 'c',
	cairo: 'cairo',
	clj: 'clojure',
	cljs: 'clojure',
	cljc: 'clojure',
	cpp: 'cpp',
	cc: 'cpp',
	cxx: 'cpp',
	hpp: 'cpp',
	config: 'toml',
	cr: 'crystal',
	cs: 'csharp',
	css: 'css',
	csv: 'csv',
	dart: 'dart',
	diff: 'diff',
	patch: 'diff',
	dockerfile: 'docker',
	env: 'dotenv',
	ex: 'elixir',
	exs: 'elixir',
	elm: 'elm',
	erb: 'erb',
	erl: 'erlang',
	hrl: 'erlang',
	fish: 'fish',
	fs: 'fsharp',
	fsx: 'fsharp',
	fsi: 'fsharp',
	gdresource: 'gdresource',
	gd: 'gdscript',
	gdshader: 'gdshader',
	feature: 'gherkin',
	gleam: 'gleam',
	go: 'go',
	graphql: 'graphql',
	gql: 'graphql',
	groovy: 'groovy',
	gradle: 'groovy',
	haml: 'haml',
	hbs: 'handlebars',
	handlebars: 'handlebars',
	hs: 'haskell',
	lhs: 'haskell',
	ini: 'ini',
	cfg: 'ini',
	conf: 'ini',
	java: 'java',
	js: 'javascript',
	mjs: 'javascript',
	cjs: 'javascript',
	json: 'json',
	json5: 'json5',
	jsonc: 'jsonc',
	jsx: 'jsx',
	kt: 'kotlin',
	kts: 'kotlin',
	tex: 'latex',
	less: 'less',
	lisp: 'lisp',
	lsp: 'lisp',
	lua: 'lua',
	makefile: 'make',
	mk: 'make',
	md: 'markdown',
	markdown: 'markdown',
	m: 'matlab',
	mdx: 'mdx',
	mermaid: 'mermaid',
	nginx: 'nginx',
	nix: 'nix',
	nu: 'nushell',
	mm: 'objective-cpp',
	ml: 'ocaml',
	mli: 'ocaml',
	pas: 'pascal',
	pp: 'pascal',
	pl: 'perl',
	pm: 'perl',
	php: 'php',
	pcss: 'postcss',
	ps1: 'powershell',
	psm1: 'powershell',
	prisma: 'prisma',
	pro: 'prolog',
	proto: 'proto',
	pug: 'pug',
	jade: 'pug',
	purs: 'purescript',
	py: 'python',
	pyw: 'python',
	r: 'r',
	R: 'r',
	razor: 'razor',
	cshtml: 'razor',
	regexp: 'regexp',
	s: 'riscv',
	rb: 'ruby',
	rbw: 'ruby',
	rs: 'rust',
	sass: 'sass',
	scala: 'scala',
	sc: 'scala',
	scm: 'scheme',
	ss: 'scheme',
	scss: 'scss',
	sh: 'shellscript',
	bash: 'shellscript',
	zsh: 'shellscript',
	sol: 'solidity',
	sql: 'sql',
	styl: 'stylus',
	svelte: 'svelte',
	swift: 'swift',
	tf: 'terraform',
	tfvars: 'terraform',
	toml: 'toml',
	tsx: 'tsx',
	twig: 'twig',
	ts: 'typescript',
	vue: 'vue',
	wasm: 'wasm',
	wat: 'wasm',
	xml: 'xml',
	yaml: 'yaml',
	yml: 'yaml',
	zig: 'zig'
};

export const SHIKI_LANGUAGES = Object.values(EXTENSION_TO_LANG);

export const BASE_IGNORE_LIST = dedent`
.git
.husky
node_modules
.vscode
.svelte-kit
.next
.turbo
.astro
target
`;
